In [1]:
# sentdex pyTorch Video 1 of 8
# from: https://www.youtube.com/watch?v=BzcBsTou0C0&list=PLQVvvaa0QuDdeMyHEYc0gxFpYwHY2Qfdh

In [2]:
import torch

In [3]:
x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x*y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([2,5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
x.shape

torch.Size([2, 5])

In [6]:
y = torch.rand([2,5])
y

tensor([[0.4711, 0.1194, 0.1257, 0.4565, 0.6285],
        [0.3550, 0.6059, 0.4233, 0.1946, 0.1031]])

In [7]:
# Flatten operation view([dimension]) of y
y.view([1,10])

tensor([[0.4711, 0.1194, 0.1257, 0.4565, 0.6285, 0.3550, 0.6059, 0.4233, 0.1946,
         0.1031]])